stages:
  - build

variables:
  REGISTRY: docker.io
  IMAGE_NAME: dejanualex/appserver
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

build-and-push:
  stage: build
  image: docker:24-dind
  services:
    - docker:24-dind
  only:
    - main
  before_script:
    - echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin $REGISTRY
  script:
    # Extract commit SHA and create tags
    - COMMIT_SHA=$(git rev-parse --short HEAD)
    - IMAGE_SHA_TAG="$REGISTRY/$IMAGE_NAME:sha-$COMMIT_SHA"
    - IMAGE_LATEST_TAG="$REGISTRY/$IMAGE_NAME:latest"
    
    # Build and push with both tags
    - docker build -t $IMAGE_SHA_TAG -t $IMAGE_LATEST_TAG .
    - docker push $IMAGE_SHA_TAG
    - docker push $IMAGE_LATEST_TAG
  after_script:
    - docker logout $REGISTRY
